fallback-grpc-addr: 127.0.0.1:3030
dial-grpc-timeout: 10
order:
  service-name: order
  server-to-run: http
  http-addr: 127.0.0.1:8080
  grpc-addr: 127.0.0.1:5002

stock:
  service-name: stock
  server-to-run: grpc
  http-addr: 127.0.0.1:8081
  grpc-addr: 127.0.0.1:5003

payment:
  service-name: payment
  server-to-run: http
  http-addr: 127.0.0.1:8282
  grpc-addr: 127.0.0.1:5004

kitchen:
  service-name: kitchen
  server-to-run: http
  http-addr: 127.0.0.1:8083
  grpc-addr: 127.0.0.1:5005

consul:
  addr: 127.0.0.1:8500

rabbitmq:
  user: guest
  password: guest
  host: 127.0.0.1
  port: 5672
  max-retry: 3

jaeger:
  url: "http://127.0.0.1:14268/api/traces"

mongo:
  user: root
  password: password
  host: 127.0.0.1
  port: 27017
  db-name: "order"
  coll-name: "order"

mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3307
  dbname: "gorder"

redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 1000

stripe-key: "${STRIPE_KEY}"
endpoint-stripe-secret: "${ENDPOINT_STRIPE_SECRET}"
